### ISSUE TITLE
How to use plugins?

### ISSUE THREAD

**Issue by screendriver** [microapps/gatsby-plugin-react-i18next#1]
Is it possible to use [i18next plugins](https://www.i18next.com/overview/api#use)? For example I want to use [i18next-http-backend](https://github.com/i18next/i18next-http-backend) to only load locales when they are really needed by the user instead of having all of them loaded immediately at once. A user from Germany for example does not change the language to English most of the time and therefore doesn't need the English locales loaded in memory.

**Comment by jimmyn** [comment]
This plugin generates a separate page for each locale so they are not loaded all at once. A user from Germany will not load the English locale. He will be redirected to `/de` page that is statically generated with German locale. Then if he switches locale to Spanish he will only load `page_data.json` with Spanish translation.

You can see it in the demo: [es/page_data.json](https://5ecd0801489011000849a7db--kind-lichterman-5edcb4.netlify.app/page-data/es/page-data.json)

The idea behind this plugin is that it does not require to add graphql queries to fetch locales. Everything is done automatically.

**Comment by screendriver** [comment]
Awesome! 👍  This is something that I wanted exactly to hear 😎 

> The idea behind this plugin is that it does not require to add graphql queries to fetch locales

That was exactly the reason why I was looking for another i18next Gatsby plugin and found your Gatsby plugin today accidentally on [npmjs.com](https://www.npmjs.com). Great work! You're plugin was exactly what I was looking for 🎉
