### ISSUE TITLE
[help] changing pages' content based on current language

### ISSUE THREAD

**Issue by dalxds** [microapps/gatsby-plugin-react-i18next#10]
Thanks again for your plugin! It's been the best one I've tried yet on gatsby!
So, I need some guidance on how to change the content of each page based on the current language of the site. 
Since the plugin, handles the routing I don't know how to implement something like this.

So, what I'm tryin to do is: 
I fetch my data from .yaml files. I query them through graphql using the graphql-yaml-transformer plugin. 
I have a data-langKey.yaml file for each language.
And then a gatsby Page Component that uses the data parsed from the yaml files to show the information.
So, how can I use gatsby, graphql and the current component to change the data when someone changes the language. 
Normally, I would do something with the gatsby-node API, but now the current plugin handles much of the stuff by itself so I don't know how to use the plugin to handle the data stuff.

Thanks for any help!
Truly appreciated!

Dimitris

**Comment by jimmyn** [comment]
Hi, thanks for the feedback. 

In [v0.0.19](https://github.com/microapps/gatsby-plugin-react-i18next/releases/tag/v0.0.19) I've added `language` to the page context directly. So you can use it as a query variable.

```js
export const query = graphql`
  query($language: String!) {
    dataYaml(language: { eq: $language }) {
      ...
    }
  }
`;
```

I suppose this should do the trick

**Comment by dalxds** [comment]
That's great! It worked! Thanks!
