### ISSUE TITLE
What’s the recommended way to use translations inside components?

### ISSUE THREAD

**Issue by marijoo** [microapps/gatsby-plugin-react-i18next#107]
I’m wondering what’s the recommended way to use translations inside components. Is there any way to use `StaticQuery` or should one always use a `graphql` query inside pages and just use `<Trans />` in components?

Thank you!

**Comment by stevensacks** [comment]
As stated in the documentation, the graphql query on the page component is all that is necessary to make translations available to all components on that page via either `<Trans>` or the `useTranslation()` or `useI18Next()` hooks.

**Comment by ntelkedzhiev** [comment]
@stevensacks I think the question was more about "Can you use translations WITHOUT having a query on the page level?". For example, in my case, I have a header and also other elements that are returned from `wrapPageElement` inside `gatsby-browser.js`. So then the question is how can the translation be loaded into i18n with a query without a page.

**Comment by stevensacks** [comment]
I didn’t build this plugin. You’re welcome to look at the source code, as I did, to see how it works. According to the documentation, the answer appears to be no. You’re using the plugin in a way it was not intended to be used, so you’re going to have to do the extra legwork yourself to figure out how to do that. I’m not saying it can’t work the way you want to use it. I have no idea if it can or not. There may well be a solution for your specific use case that the plugin did not account for.

What I suggest is read the source code, fork the repo, figure out what changes are required to support what you want it to do that do not break the current way it works, and then submit a PR for review.

**Comment by jimmyn** [comment]
@ntelkedzhiev at the beginning this plugin was built to load translations without graphql query but it causes multiple problems

- no live reload
- incremental updates do not work 
- translations are embedded in the page data and cannot be loaded per page

To summarize: if you really need to load translation without the graphql you need to check the old versions of this plugin, if you want to use translations inside the component, you need to load them into the page where you use this component. For example, if you have a common header component for all pages, you can create a translation namespace `common` (just a file named `common.json` and then include it in the translations query on each page.
