### ISSUE TITLE
Can we support language browser detection

### ISSUE THREAD

**Issue by cakasuma** [microapps/gatsby-plugin-react-i18next#11]
Is there any way for me to include i18next detection plugin, its not available in the plugin options

**Comment by cakasuma** [comment]
should i open PR to add .use(LanguageDetector)?

**Comment by jimmyn** [comment]
There is language detection, just that it is implemented differently ([check this line](https://github.com/microapps/gatsby-plugin-react-i18next/blob/master/src/plugin/wrapPageElement.tsx#L55)). If `redirect` option is true you'll get redirected to the page with your browser detected language.

**Comment by cakasuma** [comment]
nice, thank you
