### ISSUE TITLE
Include default LANG in url?

### ISSUE THREAD

**Issue by Fasani** [microapps/gatsby-plugin-react-i18next#120]
Sorry, there was no discussion board so I open a question as an issue.

I wonder can I always have the default lang included?

The site will have 2 languages:
```
www.mysite.com/en/content << defualt
www.mysite.com/fr/content
```

**Comment by leduchung** [comment]
@Fasani I think you always have the default lang included. You will also have a no-lang path as a bonus. Then it is up to you how to use them.
```
www.mysite.com/content << bonus
www.mysite.com/en/content << default
www.mysite.com/fr/content
```
