### ISSUE TITLE
Respect Gatsby's `trailingSlash` option

### ISSUE THREAD

**Issue by bicstone** [microapps/gatsby-plugin-react-i18next#127]
`trailingSlash` option has been added by gatsby.

https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#trailingslash
https://github.com/gatsbyjs/gatsby/discussions/34205

The current behavior is always add trailing slashes to each URL regardless of the `trailingSlash` option.

https://github.com/microapps/gatsby-plugin-react-i18next/blob/10d2a08861248daeec6c6589d7d89c16a506fdab/src/Helmet.tsx#L7-L10

Is it possible to be able to respect Gatsby's `trailingSlash` option and control the handling of trailing slashes?

**Comment by sklawren** [comment]
https://github.com/microapps/gatsby-plugin-react-i18next/pull/136

You'll have to add `trailingSlash` yourself to this plugin's options to match what you set it to in the gatsby config, but it will work.

**Comment by bicstone** [comment]
@sklawren Thanks!
