### ISSUE TITLE
Localized URL's?

### ISSUE THREAD

**Issue by screendriver** [microapps/gatsby-plugin-react-i18next#16]
Sorry for the stupid question but does anyone have an idea how to localize URL's together with Gatsby pages? I guess it is not possible at all but maybe someone has a workaround in his mind.

For example I have a Gatsby page called `pages/welcome.tsx`. The URL is either `my.domain/welcome` or `my.domain/de/welcome` for German or `my.domain/fr/welcome` for French visitors. Is there a way to let the URL look like `my.domain/de/willkommen` for German and for French users `my.domain/fr/bienvenue` but for all others `my.domain/welcome`?

**Comment by jimmyn** [comment]
Sorry, but this is not possible right now and I don't have plans to implement it in near future. PRs are welcome.

**Comment by logemann** [comment]
oh. How sad. This is quite problematic SEO wise....
