### ISSUE TITLE
Add support for Gatsby V5

### ISSUE THREAD

**Issue by gdams** [microapps/gatsby-plugin-react-i18next#163]
Now that Gatsby 5.0.0 is available, it would be good if this plugin could be updated to avoid the following warning:

```output
warn Plugin gatsby-plugin-react-i18next is not compatible with your gatsby version 5.0.0 - It requires gatsby@^4.16.0
```

Thanks, let me know if I can do anything to help?

**Comment by tenisjavier** [comment]
I used it on my website and it broke with Gatsby 5. We need this update 🙏

**Comment by madfcat** [comment]
Can you update or should I downgrade the gatsby version?
Any alternatives btw?

**Comment by gdams** [comment]
I've raised a PR to add support here (https://github.com/microapps/gatsby-plugin-react-i18next/pull/166).

I'll see if @jimmyn is interested in accepting it. If not then I'll consider forking the npm module.

For now, if people want to test my changes please update their package.json file to use:

```json
{
  "dependencies": {
    "gatsby-plugin-react-i18next": "gdams/gatsby-plugin-react-i18next#gatsby5"
  }
}
```

Any feedback is most welcome
