### ISSUE TITLE
[getLanguageFromPath] Language extracted from path may not be a valid language code

### ISSUE THREAD

**Issue by jenkin** [microapps/gatsby-plugin-react-i18next#19]
Following the use case described in #9 , I have these page paths:

1. `/` -> home in default language (`it` from `pages/index.js`)
2. `/en/` -> home in english language (from `pages/en/index.js`)
3. `/page-1/` -> a simple page from remote CMS created by Gatsby `createPage` method in default language
4. `/en/page-1` -> a simple page from remote CMS created by Gatsby `createPage` method in english language
5. `/blog/post-1` -> a simple post from remote CMS created by Gatsby `createPage` method in default language
6. `/en/blog/post-1` -> a simple post from remote CMS created by Gatsby `createPage` method in english language

Using `matchPath: '/:lang?/(.*)',` and `getLanguageFromPath: true` in plugin configuration I can catch all paths, but in 3. and 5. the extracted languages are `page-1` and `blog` and I see localization keys instead of translations.

I wish default language was extracted when `:lang` parameter is missing OR doesn't match any supported languages listed in plugin options. I think the problem is in [src/plugin/onCreatePage.ts#L90](https://github.com/microapps/gatsby-plugin-react-i18next/blob/master/src/plugin/onCreatePage.ts#L90), so I suggest [this patch](https://github.com/microapps/gatsby-plugin-react-i18next/compare/master...Dataninja:feature/validate-language-from-path).

Of course, if you want, I can send you a PR.

**Comment by jimmyn** [comment]
@jenkin Hey, sorry for the late response, looks good to me, please create a PR.
