### ISSUE TITLE
Use my own version of i18next?

### ISSUE THREAD

**Issue by screendriver** [microapps/gatsby-plugin-react-i18next#2]
Is it possible to use my own version of `i18next` and `react-i18next`? Or does this plugin always use the version that gets shipped with the plugin itself?

[Other plugins](https://www.npmjs.com/package/@dontepsu/gatsby-plugin-awesome-i18next) for example are capable of using the version that is installed in the consuming repository.

**Comment by jimmyn** [comment]
@screendriver should be fixed in the last release
