### ISSUE TITLE
Refreshing the page twice

### ISSUE THREAD

**Issue by StefanSelfTaught** [microapps/gatsby-plugin-react-i18next#24]
When I change the language and then revisiting the website it refreshes the page to detect the language I selected.

Can be fixed?

**Comment by ashnamuh** [comment]
[Related issue](https://github.com/i18next/react-i18next/issues/1184)

**Comment by ashnamuh** [comment]
It seems like `gatsby-plugin-react-i18next` always render React App on the first language detection. Then language redirection coccur

See below

https://github.com/microapps/gatsby-plugin-react-i18next/blob/master/src/plugin/wrapPageElement.tsx

**Comment by StefanSelfTaught** [comment]
I think you can set the `redirect` option to false in `gatsby-config.js`.

From the docs: if the value is true, / or /page-2 will be redirected to the user’s preferred language router. e.g) /es or /es/page-2. Otherwise, the pages will render defaultLangugage language. Default is true

**Comment by jimmyn** [comment]
This plugin is using JS redirects. But as gatsby generates static pages for all languages you can set up server-side redirects depending on where you host your app. For example, you can redirect customers based on browser accepted language.
