### ISSUE TITLE
Possible to have languages not part of the url?

### ISSUE THREAD

**Issue by HenrikDK2** [microapps/gatsby-plugin-react-i18next#29]
I would like the url to be "www.test.com/something" and not "www.test.com/es/something".

**Comment by sanju-developer** [comment]
Hello @HenrikDK2 , but this will lower down your project SEO value.

**Comment by jimmyn** [comment]
@HenrikDK2 the main purpose of this plugin is to generate static SEO friendly translations. If you don't need that you can simply use [react.i18next](https://react.i18next.com/). It will work just fine with Gatsby.
