### ISSUE TITLE
[TypeScript] Cannot find module './types'

### ISSUE THREAD

**Issue by screendriver** [microapps/gatsby-plugin-react-i18next#3]
I'm using TypeScript in my project but unfortunately since I installed `gatsby-plugin-react-i18next` I get following compilation error:

```sh
> tsc

node_modules/gatsby-plugin-react-i18next/dist/i18nextContext.d.ts:2:32 - error TS2307: Cannot find module './types' or its corresponding type declarations.

2 import { I18NextContext } from './types';
```

It seems that you forgot to deploy that directory to npm?

**Comment by screendriver** [comment]
Ah I guess I know the problem:

https://github.com/microapps/gatsby-plugin-react-i18next/blob/6740e9d486b013dbad4da9d84e5d3aeeeeb329aa/src/types.d.ts

is a `*.d.ts` file and TypeScript declaration files does not get copied to the output directory. In your case it is your `build:defs` script

```json
"build:defs": "tsc --declaration --outDir dist --emitDeclarationOnly"
```

The solution for that would be to just rename `types.d.ts` to `types.ts` **or** copy that single file manually to `dist/`.

**Comment by jimmyn** [comment]
@screendriver should be fixed in the last release

**Comment by screendriver** [comment]
Now I'm getting

```sh
```
