### ISSUE TITLE
Data Splitting, page-data by pages and namespaces.

### ISSUE THREAD

**Issue by AlexTimofeyev** [microapps/gatsby-plugin-react-i18next#31]
I use namespaces and have a big `page-data` file size because of each page continents the same `source` for each localization. f.e:
`page-data` for page1 and page2 the same:
`
en: {page1: {...}, page2: {...}, ...}
`
I use
`
const { t } = useI18next('page1');
`

Is it possible to separate, to fetch data that will be relative to the exact page only? 
page-data/en/page1/page-data.json
`
en: {page1: {...}}
`
Thanks a lot :)

**Comment by jimmyn** [comment]
Not for now, but this is on the roadmap, I'm sorry but I don't have time lately to work on this. PR's are always welcome.

**Comment by jimmyn** [comment]
Fixed by #43
