### ISSUE TITLE
Usage example with i18next's language detector middleware.

### ISSUE THREAD

**Issue by DimiMikadze** [microapps/gatsby-plugin-react-i18next#34]
Hi, thanks for the plugin.

Is it possible to use it with [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector) middleware? If yes, could you provide an example?

**Comment by jimmyn** [comment]
It's not possible, but this plugin has language detection built it, so i18next-browser-languageDetector is not needed. If you enable the redirect feature a user will be redirected to the page in the language set in the browser, if it is supported
