### ISSUE TITLE
easy way to also translate pageName in URL

### ISSUE THREAD

**Issue by logemann** [microapps/gatsby-plugin-react-i18next#40]
Hi,

is there an easy way to also translate the page itself? Lets say i have a "aboutus.js" in /pages and the generated locale pages should be ueberuns.js or sobrenos.js (my spanish is bad ;-)).

translating content but still having an english url is kind of meaningless isnt it? At least from SEO perspective.

**Comment by logemann** [comment]
hacked something together on a fork. See the commit 
https://github.com/logemann/gatsby-plugin-react-i18next/commit/938c0dc82e7c448773e67480479d5afcd0783d9e

Dont know if its the best way to implement it, but was at least the easiest to implement. Here you can do this in configuration:

```
{
    resolve: `gatsby-plugin-react-i18next`,
    options: {
        ...
        pages: [
            {
                matchPath: '/aws-beratung',
                urlPageRewrite: new Map([
                    ["en", "/aws-consulting/"]
                ])
            }
        ]
    }
}
```

This results in a different URL on the english localized-created page. Means, my page in /pages is named aws-beratung.js (which gatsby will create at **https://mydomain/aws-beratung/** ) and the localized version will be **https://mydomain/aws-consulting/**

Happy to hear thoughts about that feature. It would be nice to have the mapping included in the JS page source which gets picked up by the plugin....

**Comment by logemann** [comment]
after digging in deeper, i dont know if i really want to make those changes. First of, the pageUrl rewrite config is one thing. When doing it properly with needed fixes in the area of sitemap.xml serialization, its quite some effort. But even if have my mappings in place in the GraphQL i18n context, then there is a lot to change in the way the useI18next() hook works and probably also fixes in the <Link> component.  

Dont know if its worth the effort at this point. Really sad that something like that was not on the table at the beginning. Seems that not many people have SEO in mind when it comes to I18N. I might reopen this thing, if there is some kind demand besides my personal one.

**Comment by jirsbek** [comment]
I've been also dissapointed about possibility of URL's localization. For me this is the only thing that's this plugin missing. Fortunately my site is just single page but I would like to use this plugin on other sites that are more complex.
