### ISSUE TITLE
Support react 17 peer dependency

### ISSUE THREAD

**Issue by plotka** [microapps/gatsby-plugin-react-i18next#45]
I see in peer dependencies there is `"react": "^16.12.0"` and I have react v17 in my project and it is breaking on npm install. Would it be possible to update to react v17 as a peer dependecy? Thanks

**Comment by jimmyn** [comment]
Done, fixed in [https://github.com/microapps/gatsby-plugin-react-i18next/releases/tag/v1.0.3](v1.0.3)
