### ISSUE TITLE
Cannot find module 'gatsby-cli/lib/reporter'

### ISSUE THREAD

**Issue by andreademasi** [microapps/gatsby-plugin-react-i18next#46]
This module seems to be required in gatsby-plugin-react-i18next\dist\plugin\onPreBootstrap.js. Do I have to install gatsby-cli?

**Comment by nestorbonilla** [comment]
Have you tried to delete the yarn.lock and install the modules again?
I did this and the error disappear.

**Comment by andreademasi** [comment]
> Have you tried to delete the yarn.lock and install the modules again?
> I did this and the error disappear.

I'm using npm and it isn't working

**Comment by andreademasi** [comment]
Same issue when using the example in the repo

**Comment by jimmyn** [comment]
I just tested it in clean setup and everything seems to be working fine, @andreademasi could you provide a minimal example?

**Comment by jimmyn** [comment]
Fixed in [v1.0.4](https://github.com/microapps/gatsby-plugin-react-i18next/releases/tag/v1.0.4)
