### ISSUE TITLE
Is there any documentation on how to use this plugin with Gatsby client-side apps?

### ISSUE THREAD

**Issue by visualjeff** [microapps/gatsby-plugin-react-i18next#47]
I understand and have had success with using this plugin with SSR rendered content, but how does it integrate with a Gatsby generated client-side app?

Questions include:
1. Do I use **gatsby-plugin-react-i18next** or  **react-i18next** in my client-side app?
2. Do I need to create a **provider** to wrap my app in the **gatsby-browser.js** file?
3. Can we use the same locale files for SSR as the client-side app?
4. Can we avoid loading the translation files via https?

Can someone point me in the right direction?  Documentation or an example?

Thank you in advance your time,

Jeff

**Comment by jimmyn** [comment]
Please read the documentation carefully.
