### ISSUE TITLE
Bug: prefered language redirect does not work with path-prefix

### ISSUE THREAD

**Issue by Shinyaigeek** [microapps/gatsby-plugin-react-i18next#50]
## Problem

`gastby-plugin-react-i18next` redirect to user's prefered language router with plugin configuration { redirect: true }.
This redirect does not work with `gatsby.js`' s pathPrefix option.

eg) when user with prefered language configuration, { en: 0.9, ja: 0.8 }, accesses `example.github.io/hoge/bar/ja/`.
Expected behavior is that site will be redirected to `example.github.io/hoge/bar/en/`.
Actual behavior is that site will be redirected to `example.github.io/hoge/bar/ja/hoge/bar/`

## Solution

I feel that https://github.com/microapps/gatsby-plugin-react-i18next/blob/eb15b5078cf95e844aaccb840a4d19ad07c2a552/src/plugin/wrapPageElement.tsx#L54 this line causes this error.

`withPrefix` will add configured `pathPrefix` to path, but also `location.pathname` in path includes `pathPrefix`

## Other

Can i pick this issue?

**Comment by jimmyn** [comment]
@Shinyaigeek PRs are always welcome, never tested it with `pathPrefix`

**Comment by ciaranmccullough** [comment]
Hi, @Shinyaigeek we are having similar issues with the redirect and path prefix! How did you implement the solution? Thanks.

**Comment by PanLydka** [comment]
Any update? Maybe only need to merge? @jimmyn
