### ISSUE TITLE
Clarify `keySeperator` option in documentation

### ISSUE THREAD

**Issue by kije** [microapps/gatsby-plugin-react-i18next#61]
In the documentation to this plugin, `keySeperator` option is set to false. Altough this is a option from `i18next`, it should be stated in the documentation that this option **SHOULD NOT** be set to false when working with nested translation keys in one's translation file.

Users of this plugin, who might not be as familiar with i18next (like me) otherwise might get confused when they copy/paste the setup code from the documentation, but using nested keys in their translation files and wonder why their translations do not get displayed

**Comment by jimmyn** [comment]
Good point, updated readme
