### ISSUE TITLE
Language fallback

### ISSUE THREAD

**Issue by user-09876** [microapps/gatsby-plugin-react-i18next#72]
Hello!

Thanks for the great plugin, it is currently my favorite setup for i18n in gatsby.

I am considering to to add support to it for a fallback language, as described in `i18next` https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

Looking at your repository, I've found this line https://github.com/microapps/gatsby-plugin-react-i18next/blob/master/src/plugin/wrapPageElement.tsx#L111 which seems to setup i18next for using the default language as a fallback.

This solution is pretty neat, though we could enhance it to support the i18next "classic" options.

I am curious what is your opinion on this feature, and how you would see it implemented.

I am not exactly sure where to start, but would love to look a bit more at it with your advices/guidance.

Thanks in advance,
cheers

PS: i've noted from closed PR that you mention that this feature is not supported yet, and that you'd welcome a PR ([here](https://github.com/microapps/gatsby-plugin-react-i18next/issues/25#issuecomment-731779618), [there](https://github.com/microapps/gatsby-plugin-react-i18next/issues/6#issuecomment-647629167))
PS.2: it seems that the reason the "fallback" language is "not working" could be that the default language data is not loaded or passed to the ` wrapPageElement.tsx ` component? Maybe something to be done in `createNode`?

**Comment by hugurp** [comment]
Hum, actually it seems that on a page graphql query, not specifying the `$language` variable, returns all locales, and then allow the fallback on the correct default language.

```
export const query = graphql`
  query {
    locales: allLocale {
      edges {
        node {
          ns
          data
          language
        }
      }
    }
  }
`;
```

**Comment by saintasia** [comment]
If the site is multilingual then you'd be loading up multiple languages with this approach which isn't ideal, the context has i18n data including fallback language so it could probably be exposed at the filter level and passed as a second parameter to only load 2
