### ISSUE TITLE
Add option to disable page creation for each language

### ISSUE THREAD

**Issue by jenkin** [microapps/gatsby-plugin-react-i18next#9]
I know that "support multi-language url routes in a single page component" is the main feature of this plugin, but if content and paths are managed by an external system (ie. wordpress with [wpgraphql](https://www.wpgraphql.com/) and [polylang](https://polylang.pro/)) that feature becomes a problem. For example, if wpgraphql returns a page with original path `/en/page-1`, gatsby creates multiple pages with `/en/en/page-1`, `/it/en/page-1`, and so on.

I made a little change to make optional the creation of localized paths (`localizedPaths` option), without change the default behavior. In this case, language is extracted from original path with a custom function (`languageFromPath` option). You can see it [here](https://github.com/Dataninja/gatsby-plugin-react-i18next/commit/3cd33e9e3261f3288508b07db2bd73a94ba889e3).

Of course, if you want, I can send you a PR.

**Comment by jimmyn** [comment]
Hi, thanks for the contribution, I will appreciate a PR, but I think your approach is all or nothing. Maybe we can add another option to specify a regex to enable this feature only for some paths.

Imagina the use case where you have a landing page that you want to automatically translate to all available languages, but you also have a blog section that fetches posts from some CRM. I think it would be handy to allow a user to specify 

```
localizedPaths: /^\/([a-z]{2})\/blog/
```

**Comment by jenkin** [comment]
Good point, in the latest commit I changed `localizedPaths` from boolean to regexp and now `onCreatePage` test for regexp match of path.

**Comment by jenkin** [comment]
I notice there is also a problem with `Link` component, it ignores this new option and prepend language to all linked routes, breaking links... :thinking:

**Comment by jimmyn** [comment]
@jenkin this should be solved in the latest release. Check new [pages option](./README.md#how-to-exclude-pages-that-already-have-language-key-in-path).
